version: '3.1'

services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye
    tty: true
    volumes:
      - ..:/workspace:cached
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - '../.db:/var/lib/postgresql/data'
    ports:
      - '8432:5432'